#!/bin/bash
#PBS -l nodes=1:ppn=12:gpus=1
#PBS -l walltime=12:00:00
#PBS -o /gs/project/eeg-641-aa/enewel3/entity-embeddings/src/embedder/pbs/enoise-epretrain.stdout
#PBS -e /gs/project/eeg-641-aa/enewel3/entity-embeddings/src/embedder/pbs/enoise-epretrain.stderr
#PBS -N enoise-epretrain

# Load modules, go to source dir, activate virtualenv
module load Python/2.7.10 CUDA/7.5.18 cuDNN/5.0-ga
cd /gs/project/eeg-641-aa/enewel3/entity-embeddings/src/embedder 
source ../../env/bin/activate

# Run the model
THEANO_FLAGS='floatX=float32,device=gpu' python train_r2v.py \
command=train \
save_dir=/gs/project/eeg-641-aa/enewel3/entity-embeddings/data/enoise-epretrain \
min_frequency=30 \
macrobatch_size=1000000 \
num_embedding_dimensions=300 \
num_processes=12 \
max_queue_size=3 \
num_epochs=4 \
entity_noise_ratio=0.5
