#!/bin/bash
#PBS -l nodes=1:ppn=12:gpus=1
#PBS -l walltime=12:00:00
#PBS -o /gs/project/eeg-641-aa/enewel3/entity-embeddings/src/embedder/pbs/enoise-epretrain-between.stdout
#PBS -e /gs/project/eeg-641-aa/enewel3/entity-embeddings/src/embedder/pbs/enoise-epretrain-between.stderr
#PBS -N enoise-epretrain-between

# Load modules, go to source dir, activate virtualenv
module load Python/2.7.10 CUDA/7.5.18 cuDNN/5.0-ga
cd /gs/project/eeg-641-aa/enewel3/entity-embeddings/src/embedder 
source ../../env/bin/activate

# Define variables
save_dir=/gs/project/eeg-641-aa/enewel3/entity-embeddings/data/enoise-epretrain-between

# Run the model
THEANO_FLAGS='floatX=float32,device=gpu' python train_r2v.py \
command=train \
save_dir=$save_dir \
min_frequency=30 \
macrobatch_size=500000 \
num_embedding_dimensions=300 \
num_processes=12 \
max_queue_size=1 \
num_epochs=4 \
entity_noise_ratio=0.5 \
signal_sample_mode=between \
len_context=6

python sanity_check.py embeddings_dir=$save_dir

