#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=24:00:00
#PBS -o /gs/project/eeg-641-aa/enewel3/entity-embeddings/src/embedder/pbs/generate-token-pmi.stdout
#PBS -e /gs/project/eeg-641-aa/enewel3/entity-embeddings/src/embedder/pbs/generate-token-pmi.stderr
#PBS -N pmi

# Load modules, go to source dir, activate virtualenv
cd /gs/project/eeg-641-aa/enewel3/entity-embeddings/src/embedder 

module load Python/2.7.10
source /gs/project/eeg-641-aa/enewel3/entity-embeddings/env/bin/activate 

# Run the model
python generate_entity_pair_vocab.py
